### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by arisprung** [IvonaSoftware/ivona-speechcloud-sdk-java#4]
Is there a good example for implementation for android? I keep on getting this error

java.lang.NoSuchMethodError: No static method setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V in class Lorg/apache/http/params/HttpConnectionParams; or its super classes (declaration of 'org.apache.http.params.HttpConnectionParams' appears in /system/framework/framework.jar:classes2.dex)
                                                                                 at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:95)
                                                                                 at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:198)
                                                                                 at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:129)
                                                                                 at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:113)
                                                                                 at com.ivona.services.tts.IvonaSpeechCloudClient.<init>(IvonaSpeechCloudClient.java:152)
                                                                                 at com.ivona.services.tts.IvonaSpeechCloudClient.<init>(IvonaSpeechCloudClient.java:141)
                                                                                 at ivonatestsecond.com.ivonasecond.MainActivity.init(MainActivity.java:64)
                                                                                 at ivonatestsecond.com.ivonasecond.MainActivity.onCreate(MainActivity.java:24)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

**Comment by reidisaki** [comment]
i can't find a fix for this either. but i think we're all bouncing around on SO and this and other sites with no one able to fix this. Pretty much ostracized all android
